services:
  - type: web
    name: nba-analytics
    env: node
    buildCommand: ./build.sh
    startCommand: node server/render-production.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nba-analytics-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: false

databases:
  - name: nba-analytics-db
    databaseName: nba_analytics
    user: nba_user